figure,plot(VV{1,1})
title('\it{Voltage vs time plot}','FontSize',16)
xlabel('time','FontSize',16)
ylabel('Voltage','FontSize',16)
figure,plot(JNa{1,1})
xlabel('time','FontSize',16)
ylabel('Sodium current','FontSize',16)
title('\it{Sodium current with time}','FontSize',16)
figure,plot(JK{1,1})
xlabel('time','FontSize',16)
ylabel('potassium current','FontSize',16)
title('\it{Potassium current with time}','FontSize',16)
figure,plot(JL{1,1}) 
xlabel('time','FontSize',16)
ylabel('Leakage current','FontSize',16)
title('\it{leakage current}','FontSize',16)
figure,plot(mm{1,1})
xlabel('time','FontSize',16)
ylabel('m variable','FontSize',16)
title('\it{m with time}','FontSize',16)
figure,plot(nn{1,1})
xlabel('time','FontSize',16)
ylabel('n variable','FontSize',16)
title('\it{n with time}','FontSize',16)
figure,plot(hh{1,1})
xlabel('time','FontSize',16)
ylabel('h variable','FontSize',16)
title('\it{h with time}','FontSize',16)